#!/bin/bash

# Android Emulator confg. https://developer.android.com/studio/install?hl=pt-br
[ -d "$HOME/Library/Android/sdk" ] && ANDROID_SDK=$HOME/Library/Android/sdk || ANDROID_SDK=$HOME/Android/Sdk
echo "export ANDROID_SDK=$ANDROID_SDK" >>~/$([[ $SHELL == *"bash" ]] && echo '.bashenv' || echo '.bashrc')

# Asdf confg.
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# Confg. NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# Confg. Yarn
export PATH="$PATH:$(yarn global bin)"
